In [1]:
import pandas as pd

In [3]:
data=pd.read_csv("creditcard.csv")

In [5]:
data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [7]:
pd.options.display.max_columns = None

In [9]:
data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,-0.551600,-0.617801,-0.991390,-0.311169,1.468177,-0.470401,0.207971,0.025791,0.403993,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,1.612727,1.065235,0.489095,-0.143772,0.635558,0.463917,-0.114805,-0.183361,-0.145783,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,0.624501,0.066084,0.717293,-0.165946,2.345865,-2.890083,1.109969,-0.121359,-2.261857,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,-0.226487,0.178228,0.507757,-0.287924,-0.631418,-1.059647,-0.684093,1.965775,-1.232622,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,-0.822843,0.538196,1.345852,-1.119670,0.175121,-0.451449,-0.237033,-0.038195,0.803487,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [11]:
data.tail

<bound method NDFrame.tail of             Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193
...          ...        ...        ...       ...       ...       ...
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546

              V6        V7        V8        V9       V10       V11       V12  \
0       0.462388  0.239599  0.098698  0.363787  0.090794 -0.551600 -0.617801
1      -0.082361 -0.078803  0.085102 -0.255425 -0.166974  1.612727  1.065235
2       1.800499  0.791461  0.247676 -1.514654  0.207643  0.624501  0.066084
3       1.247203  0.237609  0.377436 -1.387024 -0.054952 -0.226487  0.178228
4       0.095921  0.592941 -0.270533  0.817739  0.753074 -0.822843  0.538196
...          ...       ...       ...       ...       ...       ...       ...
284802 -2.606837 -4.918215  7.305334  1.914428  4.356170 -1.593105  2.711941
284803  1.058415  0.024330  0.294869  0.584800 -0.975926 -0.150189  0.915802
284804  3.031260 -0.296827  0.708417  0.432454 -0.484782  0.411614  0.063119
284805  0.623708 -0.686180  0.679145  0.392087 -0.399126 -1.933849 -0.962886
284806 -0.649617  1.577006 -0.414650  0.486180 -0.915427 -1.040458 -0.031513

             V13       V14       V15       V16       V17       V18       V19  \
0      -0.991390 -0.311169  1.468177 -0.470401  0.207971  0.025791  0.403993
1       0.489095 -0.143772  0.635558  0.463917 -0.114805 -0.183361 -0.145783
2       0.717293 -0.165946  2.345865 -2.890083  1.109969 -0.121359 -2.261857
3       0.507757 -0.287924 -0.631418 -1.059647 -0.684093  1.965775 -1.232622
4       1.345852 -1.119670  0.175121 -0.451449 -0.237033 -0.038195  0.803487
...          ...       ...       ...       ...       ...       ...       ...
284802 -0.689256  4.626942 -0.924459  1.107641  1.991691  0.510632 -0.682920
284803  1.214756 -0.675143  1.164931 -0.711757 -0.025693 -1.221179 -1.545556
284804 -0.183699 -0.510602  1.329284  0.140716  0.313502  0.395652 -0.577252
284805 -1.042082  0.449624  1.962563 -0.608577  0.509928  1.113981  2.897849
284806 -0.188093 -0.084316  0.041333 -0.302620 -0.660377  0.167430 -0.256117

             V20       V21       V22       V23       V24       V25       V26  \
0       0.251412 -0.018307  0.277838 -0.110474  0.066928  0.128539 -0.189115
1      -0.069083 -0.225775 -0.638672  0.101288 -0.339846  0.167170  0.125895
2       0.524980  0.247998  0.771679  0.909412 -0.689281 -0.327642 -0.139097
3      -0.208038 -0.108300  0.005274 -0.190321 -1.175575  0.647376 -0.221929
4       0.408542 -0.009431  0.798278 -0.137458  0.141267 -0.206010  0.502292
...          ...       ...       ...       ...       ...       ...       ...
284802  1.475829  0.213454  0.111864  1.014480 -0.509348  1.436807  0.250034
284803  0.059616  0.214205  0.924384  0.012463 -1.016226 -0.606624 -0.395255
284804  0.001396  0.232045  0.578229 -0.037501  0.640134  0.265745 -0.087371
284805  0.127434  0.265245  0.800049 -0.163298  0.123205 -0.569159  0.546668
284806  0.382948  0.261057  0.643078  0.376777  0.008797 -0.473649 -0.818267

             V27       V28  Amount  Class
0       0.133558 -0.021053  149.62      0
1      -0.008983  0.014724    2.69      0
2      -0.055353 -0.059752  378.66      0
3       0.062723  0.061458  123.50      0
4       0.219422  0.215153   69.99      0
...          ...       ...     ...    ...
284802  0.943651  0.823731    0.77      0
284803  0.068472 -0.053527   24.79      0
284804  0.004455 -0.026561   67.88      0
284805  0.108821  0.104533   10.00      0
284806 -0.002415  0.013649  217.00      0

[284807 rows x 31 columns]>

In [13]:
data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,4.356170,-1.593105,2.711941,-0.689256,4.626942,-0.924459,1.107641,1.991691,0.510632,-0.682920,1.475829,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,-0.975926,-0.150189,0.915802,1.214756,-0.675143,1.164931,-0.711757,-0.025693,-1.221179,-1.545556,0.059616,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,-0.484782,0.411614,0.063119,-0.183699,-0.510602,1.329284,0.140716,0.313502,0.395652,-0.577252,0.001396,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,-0.399126,-1.933849,-0.962886,-1.042082,0.449624,1.962563,-0.608577,0.509928,1.113981,2.897849,0.127434,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,-0.915427,-1.040458,-0.031513,-0.188093,-0.084316,0.041333,-0.302620,-0.660377,0.167430,-0.256117,0.382948,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [15]:
data.shape

(284807, 31)

In [17]:
print("number of colums{}",format(data.shape[1]))

number of colums{} 31

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [21]:
data.isnull().sum

<bound method DataFrame.sum of          Time     V1     V2     V3     V4     V5     V6     V7     V8     V9  \
0       False  False  False  False  False  False  False  False  False  False
1       False  False  False  False  False  False  False  False  False  False
2       False  False  False  False  False  False  False  False  False  False
3       False  False  False  False  False  False  False  False  False  False
4       False  False  False  False  False  False  False  False  False  False
...       ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
284802  False  False  False  False  False  False  False  False  False  False
284803  False  False  False  False  False  False  False  False  False  False
284804  False  False  False  False  False  False  False  False  False  False
284805  False  False  False  False  False  False  False  False  False  False
284806  False  False  False  False  False  False  False  False  False  False

          V10    V11    V12    V13    V14    V15    V16    V17    V18    V19  \
0       False  False  False  False  False  False  False  False  False  False
1       False  False  False  False  False  False  False  False  False  False
2       False  False  False  False  False  False  False  False  False  False
3       False  False  False  False  False  False  False  False  False  False
4       False  False  False  False  False  False  False  False  False  False
...       ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
284802  False  False  False  False  False  False  False  False  False  False
284803  False  False  False  False  False  False  False  False  False  False
284804  False  False  False  False  False  False  False  False  False  False
284805  False  False  False  False  False  False  False  False  False  False
284806  False  False  False  False  False  False  False  False  False  False

          V20    V21    V22    V23    V24    V25    V26    V27    V28  Amount  \
0       False  False  False  False  False  False  False  False  False   False
1       False  False  False  False  False  False  False  False  False   False
2       False  False  False  False  False  False  False  False  False   False
3       False  False  False  False  False  False  False  False  False   False
4       False  False  False  False  False  False  False  False  False   False
...       ...    ...    ...    ...    ...    ...    ...    ...    ...     ...
284802  False  False  False  False  False  False  False  False  False   False
284803  False  False  False  False  False  False  False  False  False   False
284804  False  False  False  False  False  False  False  False  False   False
284805  False  False  False  False  False  False  False  False  False   False
284806  False  False  False  False  False  False  False  False  False   False

        Class
0       False
1       False
2       False
3       False
4       False
...       ...
284802  False
284803  False
284804  False
284805  False
284806  False

[284807 rows x 31 columns]>

In [23]:
data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [25]:
from sklearn.preprocesssing import StandardScaler

ModuleNotFoundError: No module named 'sklearn.preprocesssing'

In [27]:
from sklearn.preprocessing import StandardScaler

In [29]:
sc = StandardScaler()
data['Amount']=sc.fit_transform(pd.DataFrame(data['Amount']))

In [31]:
data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,-0.551600,-0.617801,-0.991390,-0.311169,1.468177,-0.470401,0.207971,0.025791,0.403993,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,0.244964,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,1.612727,1.065235,0.489095,-0.143772,0.635558,0.463917,-0.114805,-0.183361,-0.145783,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,-0.342475,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,0.624501,0.066084,0.717293,-0.165946,2.345865,-2.890083,1.109969,-0.121359,-2.261857,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,1.160686,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,-0.226487,0.178228,0.507757,-0.287924,-0.631418,-1.059647,-0.684093,1.965775,-1.232622,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,0.140534,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,-0.822843,0.538196,1.345852,-1.119670,0.175121,-0.451449,-0.237033,-0.038195,0.803487,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,-0.073403,0

In [33]:
data = data.drop(['Time'], axis = 1)

In [35]:
data.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,-0.551600,-0.617801,-0.991390,-0.311169,1.468177,-0.470401,0.207971,0.025791,0.403993,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,0.244964,0
1,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,1.612727,1.065235,0.489095,-0.143772,0.635558,0.463917,-0.114805,-0.183361,-0.145783,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,-0.342475,0
2,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,0.624501,0.066084,0.717293,-0.165946,2.345865,-2.890083,1.109969,-0.121359,-2.261857,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,1.160686,0
3,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,-0.226487,0.178228,0.507757,-0.287924,-0.631418,-1.059647,-0.684093,1.965775,-1.232622,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,0.140534,0
4,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,-0.822843,0.538196,1.345852,-1.119670,0.175121,-0.451449,-0.237033,-0.038195,0.803487,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,-0.073403,0

In [37]:
data.duplicated().any()

True

In [39]:
data=data.drop_duplicates()

In [41]:
data.shape

(275663, 30)

In [43]:
data['class'].value_counts()

KeyError: 'class'

In [45]:
data['Class'].value_counts()

Class
0    275190
1       473
Name: count, dtype: int64

In [49]:
import seaborn as sns
from matplotlib.pyplot as plt
plt.style.use('ggplot')

SyntaxError: invalid syntax (1297371457.py, line 2)

In [51]:
import seaborn as sns
import matplotlib.pyplot as plt
plt.style.use('ggplot')

In [ ]:
sns.countplot(data['Class'])
plt.show()

In [ ]:
X = data.drop('Class',axis = 1)

In [ ]:
X = data.drop('Class',axis = 1)
y=data['Class']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [ ]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,f1_score,precision_score,recall_score

In [ ]:
classifier = {
    "Logistic Regression":LogisticRegression(),
    "Decision Tree Classifier": DecisionTreeClassifier()
}

for name,clf in classifier.items():
    print(f"\n========={name}==============")
    clf.fir(X_train,y_train)
    y_pred = clf.predict(X_test)
    accuracy=accuracy_score(y_test,y_pred)
    print(f"\n Accuracy: {accuracy_score(y_test,y_pred)}")
    print(f"\n Precision: {precision_score(y_test,y_pred)}")
    print(f"\n Recall: {recall_score(y_test,y_pred)}")
    print(f"\n F1 Score: {f1_score(y_test,y_pred)}")

In [ ]:
#Undersampling

In [ ]:
normal = data[data['Class']==0]
fraud = data[data['Class']==1]

In [ ]:
normal.shape

In [ ]:
fraud.shape

In [ ]:
normal.sample(n=473)

In [ ]:
normal_sample.shape

In [ ]:
new data=pd.concat([normal_sample,fraud],ignore_index=True)

In [ ]:
new_data.head()

In [ ]:
new_data['Class'].value_counts()

In [ ]:
X = new_data.drop('Class',axis = 1)
y=new_data['Class']

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [ ]:
classifier = {
    "Logistic Regression":LogisticRegression(),
    "Decision Tree Classifier": DecisionTreeClassifier()
}

for name,clf in classifier.items():
    print(f"\n========={name}==============")
    clf.fir(X_train,y_train)
    y_pred = clf.predict(X_test)
    accuracy=accuracy_score(y_test,y_pred)
    print(f"\n Accuracy: {accuracy_score(y_test,y_pred)}")
    print(f"\n Precision: {precision_score(y_test,y_pred)}")
    print(f"\n Recall: {recall_score(y_test,y_pred)}")
    print(f"\n F1 Score: {f1_score(y_test,y_pred)}")

In [ ]:
#oversampling

In [ ]:
X = data.drop('Class',axis = 1)
y=data['Class']

In [ ]:
X.shape

In [ ]:
y.shape

In [ ]:
from imblearn.over_sampling import SMOTE

In [ ]:
SMOTE().fit_resample(X,y)

In [ ]:
X_res,y_res = SMOTE().fit_resample(X,y)

In [ ]:
y_res.value_counts()

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [ ]:
classifier = {
    "Logistic Regression":LogisticRegression(),
    "Decision Tree Classifier": DecisionTreeClassifier()
}

for name,clf in classifier.items():
    print(f"\n========={name}==============")
    clf.fir(X_train,y_train)
    y_pred = clf.predict(X_test)
    accuracy=accuracy_score(y_test,y_pred)
    print(f"\n Accuracy: {accuracy_score(y_test,y_pred)}")
    print(f"\n Precision: {precision_score(y_test,y_pred)}")
    print(f"\n Recall: {recall_score(y_test,y_pred)}")
    print(f"\n F1 Score: {f1_score(y_test,y_pred)}")

In [ ]:
dtc = DecisionTreeClassifier()
dtc.fit(X_res,y_res)

In [ ]:
import joblib
joblib.dump(dtc."credit_card_model.pkl")

In [ ]:
model = joblib.load("credit_card_model.pkl")

In [ ]:
pred = model.predict([[]])

In [ ]:
pred[0]

In [ ]:
if pred == 0:
    print('Normal Transaction')
else:
    print("fraud Transaction")

In [ ]:
flask,streamlit->homework